# Generated by Django 6.1.1 on 2026-09-13 10:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Description')),
                ('description', models.CharField(blank=True, help_text='Optional extra detail line', max_length=300)),
                ('account', models.CharField(choices=[('Missions & Outreach Fund', 'Missions & Outreach Fund'), ('Evangelism Materials', 'Evangelism Materials'), ('Program Logistics', 'Program Logistics'), ('General Fund', 'General Fund')], default='Missions & Outreach Fund', max_length=60)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('program_period', models.CharField(default='September 2026', max_length=40)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrgSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(default='Grace Fellowship', max_length=150)),
                ('treasurer_title', models.CharField(default='Treasurer — Grace Fellowship HQ', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Pastor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('branch', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('messenger', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BranchReportEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(max_length=40)),
                ('tithes_offerings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('special_contributions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('branch_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('treasurer_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pastor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_reports', to='dashboard.pastor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(help_text='e.g. September 2026', max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Sent', 'Sent')], default='Paid', max_length=10)),
                ('sent_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('pastor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to='dashboard.pastor')),
            ],
            options={
                'ordering': ['-sent_on'],
            },
        ),
        migrations.CreateModel(
            name='SentAllotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('channels', models.CharField(blank=True, max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('program_period', models.CharField(default='September 2026', max_length=40)),
                ('recipients', models.ManyToManyField(blank=True, related_name='sent_allotments', to='dashboard.pastor')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
